import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFGenerationOptions {
  filename?: string;
  quality?: number;
  scale?: number;
}

/**
 * Generate PDF from HTML element
 * @param elementId - ID of the HTML element to convert
 * @param options - PDF generation options
 */
export async function generatePDF(
  elementId: string,
  options: PDFGenerationOptions = {}
): Promise<void> {
  const {
    filename = 'numerology-reading.pdf',
    quality = 0.95,
    scale = 2,
  } = options;

  const element = document.getElementById(elementId);

  if (!element) {
    throw new Error(`Element with ID "${elementId}" not found`);
  }

  try {
    // Create canvas from HTML element
    const canvas = await html2canvas(element, {
      scale,
      useCORS: true,
      logging: false,
      backgroundColor: '#0A0A0F', // Match your mystical background (deep noir)
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
    });

    // Calculate PDF dimensions
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;

    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    let position = 0;

    // Convert canvas to image
    const imgData = canvas.toDataURL('image/jpeg', quality);

    // Add first page
    pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add additional pages if content is longer than one page
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Save PDF
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}

/**
 * Generate PDF with custom content sections
 * This creates a more structured PDF with better formatting
 */
export async function generateNumerologyPDF(data: {
  dob: string;
  mulank: number;
  destiny: number;
  title?: string;
}): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  let yPosition = 20;

  // Helper function to check if we need a new page
  const checkNewPage = (neededSpace: number) => {
    if (yPosition + neededSpace > pageHeight - 20) {
      pdf.addPage();
      yPosition = 20;
    }
  };

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(41, 128, 185); // Primary color
  pdf.text('Numerology Reading', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Date
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(new Date().toLocaleDateString(), pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Date of Birth
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Date of Birth: ${new Date(data.dob).toLocaleDateString()}`, 20, yPosition);
  yPosition += 10;

  // Draw divider
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, yPosition, pageWidth - 20, yPosition);
  yPosition += 15;

  // Mulank Number
  checkNewPage(30);
  pdf.setFontSize(16);
  pdf.setTextColor(41, 128, 185);
  pdf.text('Mulank (Driver) Number', 20, yPosition);
  yPosition += 10;

  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Your Mulank Number: ${data.mulank}`, 20, yPosition);
  yPosition += 20;

  // Destiny Number
  checkNewPage(30);
  pdf.setFontSize(16);
  pdf.setTextColor(41, 128, 185);
  pdf.text('Destiny Number', 20, yPosition);
  yPosition += 10;

  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Your Destiny Number: ${data.destiny}`, 20, yPosition);
  yPosition += 20;

  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by Aura Digits | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save
  const filename = data.title
    ? `${data.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`
    : `numerology-reading-${new Date().getTime()}.pdf`;

  pdf.save(filename);
}
